### ISSUE TITLE
Starting All Contributors

### ISSUE THREAD

**Issue by duskvirkus** [CodingTrain/Random-Whistle#2]
@all-contributors please add @shiffman for code

**Comment by duskvirkus** [comment]
@all-contributors please add @violetcraze for documentation

**Comment by duskvirkus** [comment]
@all-contributors please add @shiffman for code

**Comment by duskvirkus** [comment]
@all-contributors please add @violetcraze for documentation

**Comment by duskvirkus** [comment]
@all-contributors please add @violetcraze for documentation

**Comment by gruselhaus** [comment]
@all-contributors please add @gruselhaus for code
