### ISSUE TITLE
Load Seeds from JSON and web-seed

### ISSUE THREAD

**Issue by johntalton** [CodingTrain/Random-Whistle#9]
a simple load from json and render p5 

passing `?seed=<key>` will load and render a random walk given the json seed for that key value.  individual depth prop can be set for all or individual keys.

provides some level of async loading etc

[Seed Bar depth 200](https://johntalton.github.io/seedStore/?seed=foo)
[Seed Bar depth 100000](https://johntalton.github.io/seedStore/?seed=bar)

included is a implementation of seeded random for the web, as well as a connonical pseudoRanom generator that can be used to replace heavy weigh solution

**Comment by johntalton** [comment]
add [hunters](https://johntalton.github.io/seedStore/?seed=hunter) seed to demo similar output to todays stream

**Comment by shiffman** [comment]
Thanks for these suggestions from 2 years ago, wow! I'm finalizing the whistles and this page will now be a very simple thank you that receives the random number from a URL parameter.
